dodfather/dodfather/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('projects/', include('projects.urls')),
    path('admin/', admin.site.urls),
]

dodfather/projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new', views.ProjectCreateView.as_view(), name='new'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/edit', views.edit, name='edit'),
    path('<int:pk>/delete', views.delete, name='delete'),
]

dodfather/projects/models.py
from django.db import models
import datetime
from django.utils import timezone


class Project(models.Model):

    DOODLING = 'D'
    EXECUTNG = 'I'
    SUBMITTED = 'S'
    ABANDONED = 'A'
    COMPLETED = 'C'
    RESPECIFYING = 'R'
    FAILED = 'F'

    STATUS_CHOICES = [
        (DOODLING, 'Doodling'),
        (SUBMITTED, 'Submitted'),
        (EXECUTNG, 'Executing'),
        (ABANDONED, 'Abandoned'),
        (COMPLETED, 'Completed'),
        (RESPECIFYING, 'Respecifying'),
        (FAILED, 'Failed'),
    ]
    title = models.CharField(max_length=50)
    value_proposition = models.TextField(max_length=2000)
    status = models.CharField(max_length=1,
                              choices=STATUS_CHOICES,
                              default=DOODLING)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        # self.created_at = timezone.now()

    def __str__(self):
        return self.title

    # def was_published_recently(self):
    #     now = timezone.now()
    #     return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Measure(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=400)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

dodfather/projects/forms.py
from django.forms import ModelForm
from django.forms import inlineformset_factory

from .models import Project, Measure


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'value_proposition', ]


NewProjectMeasuresFormSet = inlineformset_factory(
    Project, Measure, fields=('title', 'description'), extra=3, can_delete=False)
EditProjectMeasuresFormSet = inlineformset_factory(
    Project, Measure, fields=('title', 'description'), extra=3, can_delete=True)

dodfather/projects/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, Http404

from django.utils import timezone
from django.urls import reverse
from django.views import generic
from django.contrib import messages


from .models import Project, Measure
from .forms import ProjectForm, NewProjectMeasuresFormSet, EditProjectMeasuresFormSet


class IndexView(generic.ListView):
    template_name = 'projects/index.html'
    model = Project
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q', '')
        return context

    def get_queryset(self):
        query = self.request.GET.get('q', '')
        return Project.objects.filter(title__icontains=query).order_by('-created_at')


class ProjectCreateView(generic.CreateView):
    form_class = ProjectForm
    template_name = 'projects/new.html'

    def get_context_data(self, **kwargs):
        context = super(ProjectCreateView, self).get_context_data(**kwargs)
        context['measures_form'] = NewProjectMeasuresFormSet()
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        measures_form = NewProjectMeasuresFormSet(self.request.POST)
        if form.is_valid() and measures_form.is_valid():
            return self.form_valid(form, measures_form)
        else:
            return self.form_invalid(form, measures_form)

    def form_valid(self, form, measures_form):
        self.object = form.save(commit=False)
        self.object.save()
        # saving Measure Instances by attaching the project
        measures = measures_form.save(commit=False)
        for measure in measures:
            measure.project = self.object
            measure.save()
        return HttpResponseRedirect(reverse("projects:index"))

    def form_invalid(self, form, measures_form):
        return self.render_to_response(
            self.get_context_data(form=form,
                                  measures_form=measures_form
                                  )
        )


def delete(request, pk):
    if request.method != 'POST':
        raise Http404("Must use POST on delete")
    project = get_object_or_404(Project, pk=pk)
    project.delete()
    messages.success(request, f'Deleted project {project}')
    return HttpResponseRedirect(reverse('projects:index'))


def edit(request, pk):
    # if this is a POST request we need to process the form data
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ProjectForm(request.POST, instance=project)
        measures_form = EditProjectMeasuresFormSet(
            request.POST, instance=project)

        # check whether it's valid:
        if form.is_valid() and measures_form.is_valid():
            project = form.save()
            measures_form.save()
            messages.success(request, f'Saved project {project}')
            return HttpResponseRedirect(reverse('projects:detail', args=(project.id,)))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ProjectForm(instance=project)
        measures_form = EditProjectMeasuresFormSet(instance=project)

    return render(request, 'projects/edit.html', {'form': form, 'measures_form': measures_form})


class DetailView(generic.DetailView):
    model = Project
    template_name = 'projects/detail.html'

    # Add measures into the context
    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['measures'] = Measure.objects.filter(
            project=context['project'])
        return context

dodfather/projects/templates/projects/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DODFather</title>
    <script src="https://unpkg.com/feather-icons"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
    <!-- Favicons
        <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
        <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
        <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
        <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
        <meta name="theme-color" content="#7952b3">
    -->

    <link rel="stylesheet" type="text/css" href="{% static 'projects/style.css' %}" />
  </head>
  <body>

    <!-- header -->
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">DODFather</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <form method='GET' action="{% url 'projects:index' %}" class='w-100'>
            <input class="form-control form-control-dark " type="text" placeholder="Search" aria-label="Search" name='q' value='{{query}}' >
        </form>
        <div class="navbar-nav">
            <div class="nav-item text-nowrap">
            <a class="nav-link px-3" href="#">Sign out</a>
            </div>
        </div>
    </header>


<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'projects:index'%}">
              <i data-feather="clipboard"></i>
              All Projects
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Orders
            </a>
          </li>

        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              My Projects
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Need Commitment
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Recently Delivered
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Overdue
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{% block title %}{% endblock title %}</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            {% block contextbuttons %} {% endblock %}
          </div>
        </div>
      </div>
    <!-- Pop-up Flash Messages -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
              </div>
        {% endfor %}
    {% endif %}


        <div id="content">{% block content %}{% endblock %}</div>
    </main>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>

<script>
    feather.replace()
  </script>
</body>
</html>

dodfather/projects/templates/projects/detail.html
{% extends "projects/base.html" %}

{% block title %}
    {{ project.title }}
{% endblock title%}

{% block contextbuttons %}
<a type="button" class="btn btn-sm btn-outline-secondary">Share</a>
<a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'projects:edit' project.id %}">Edit</a>
{% endblock%}

{% block content %}
    <h4>Value Proposition</h4>
    <p>{{ project.value_proposition }}</p>



    <table class="table">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Description </th>
          </tr>
        </thead>
        <tbody>
          {% for measure in measures %}
          <tr>
            <td>{{measure.title}}</td>
            <td>{{measure.description}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>


{% endblock content %}

dodfather/projects/templates/projects/edit.html
{% extends "projects/base.html" %}

{% block title %}
    Editing {{ form.instance.title}}
{% endblock title%}

{% block content %}

<form method="post">
    {% csrf_token %}

    <table class="table">
        {{ form.as_table }}
    </table>

    <table class="table">
        {{ measures_form.as_table }}
    </table>
    <input type="submit" value="Save changes">
</form>

<!-- TODO - should we allow deleting? Or should this always be abandoned? -->
<form method="post" action="{% url 'projects:delete' form.instance.id %}">
    {% csrf_token %}
    <input type="hidden" name="delete_project" value="true"/>
    <button type="submit" class="btn btn-danger">Delete Project</button>
</form>
{% endblock content %}

dodfather/projects/templates/projects/index.html
{% extends "projects/base.html" %}

{% block title %}
  Projects   {% if query %} matching {{ query}}   {% endif %}

{% endblock title%}

{% block contextbuttons %}
<a type="button" href='{% url 'projects:new' %}' class="btn btn-sm btn-primary">New</a>
{% endblock%}


{% block content %}

{% for project in object_list %}
<li>
  <a href="{% url 'projects:detail' project.id %}"
    >{{ project.title }}</a
  >
</li>
{% endfor %}



<nav aria-label="Page navigation" class="mt-3">
  <ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% else%}
        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a></li>
    {% endif %}

    {% for iterator_page in page_obj.paginator  %}
        <li class="page-item"><a class="page-link {% if iterator_page.number == page_obj.number %} active {% endif %}" href="?page={{ iterator_page.number }}">{{iterator_page.number}}</a></li>
    {% endfor%}

    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% else%}
        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a></li>
    {% endif %}

  </ul>
</nav>


{% endblock content %}

dodfather/projects/templates/projects/new.html
{% extends "projects/base.html" %}

{% block title %}
    New Project
{% endblock title%}

{% block content %}

<form method="post">
    {% csrf_token %}

    <table class="table">
        {{ form.as_table }}
    </table>

    <table class="table">
    {{ measures_form }}
    </table>
    <input type="submit" value="Create">
</form>
{% endblock content %}